
name: "dyu_fr_transformer-sp"
joeynmt_version: "2.3.0"
model_dir: "./model_dir"
use_cuda: True # False for CPU training
fp16: False

data:
    train: "./data_dir"
    dev: "./data_dir"
    test: "./data_dir"
    dataset_type: "huggingface"
    dataset_cfg:
        name: "dyu-fr"
    sample_dev_subset: 9
    src:
        lang: "dyu"
        max_length: 75
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 3000
        voc_min_freq: 2
        voc_file: "./model_dir/vocab.txt"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "./model_dir/sp.model"
    trg:
        lang: "fr"
        max_length: 40
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 3000
        voc_min_freq: 2
        voc_file: "./model_dir/vocab.txt"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "./model_dir/sp.model"
    special_symbols:
        unk_token: "<unk>"
        unk_id: 0
        pad_token: "<pad>"
        pad_id: 1
        bos_token: "<s>"
        bos_id: 2
        eos_token: "</s>"
        eos_id: 3


testing:
    #load_model: "./model_dir/best.ckpt"
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 1024
    batch_type: "token"
    max_output_length: 40
    eval_metrics: ["bleu"]
    #return_prob: "hyp"
    #return_attention: False
    sacrebleu_cfg:
        tokenize: "13a"

training:
    load_model: "./model_dir/latest.ckpt"
    #reset_best_ckpt: False
    #reset_scheduler: False
    #reset_optimizer: False
    #reset_iter_state: False
    #random_subset: 10  # Set to 0 or adjust to avoid subsampling
    random_seed: 42
    optimizer: "adamw"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "warmupinversesquareroot"
    learning_rate_warmup: 100
    learning_rate: 0.0005
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    loss: "crossentropy"
    batch_size: 4096
    batch_type: "token"
    batch_multiplier: 4
    #early_stopping_metric: "bleu" #"ppl"-closely tracks training loss
    #early_stopping_patience: 500 # Number of epochs to wait for improvement
    epochs: 500
    #updates: 550 #-overrides early stopping epochs
    validation_freq: 500
    logging_freq: 500
    overwrite: True
    shuffle: True
    print_valid_sents: [0, 1, 2, 3]
    #keep_best_ckpts: 3
    keep_best_ckpts: 0  # Change this to 0 so that only the latest checkpoint is saved


model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.0
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.1
        layer_norm: "pre"
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0.0
        # typically ff_size = 4 x hidden_size
        hidden_size: 256
        ff_size: 1024
        dropout: 0.1
        layer_norm: "pre"

